### PR TITLE
Profile firebase functions

### PR DESCRIPTION
**Pull request by ppondo**

### CODE REVIEW

**Comment by Elkfrawy** [comment]
@ppondo I get this error when I have liked/wish movies:
image

Please merge the main branch to yours and make sure can display movies correctly. In addition, I think we will need to improve the UI of the page.

**Comment by ppondo** [comment]
@Elkfrawy that should be fixed with this PR it just needs to be reviewed

**Comment by ppondo** [comment]
I'll update the UI, I just wanted to merge the functional profile page/edit form

**Comment by ppondo** [comment]
ignore my other comments i see an issue

**Comment by swseverance** [comment]
@ppondo instead of using axios directly in the component can you add the methods you need to moviesService? It has logic to call the right url and attach the token. Thanks!

**Pull request closed without merging**
